-- Add confirmation email HTML field to agent_ia_config table

ALTER TABLE public.agent_ia_config
ADD COLUMN confirmation_email_html TEXT;

-- Add comment explaining the field
COMMENT ON COLUMN public.agent_ia_config.confirmation_email_html IS 'HTML template for confirmation email generated by AI';

